### ISSUE TITLE
Endpoint

### ISSUE THREAD

**Issue by Heater711** [b1naryth1ef/sneaker#10]
What is the setting for /api/discord/interactions ?

I have a dedicated server where I launch the sneaker

**Comment by b1naryth1ef** [comment]
Whatever URL you use to access Sneaker plus that, so for example if you used `https://sneaker.blah.com` it would be `https://sneaker.blah.com/api/discord/interactions`. Keep in mind that Discord requires you to have HTTPS enabled (which can be done for free with something like [letsencrypt](https://letsencrypt.org/getting-started/) or Cloudflare.

I am considering moving the Discord integration into a separate component which would have extended functionality for interacting with DCS (via [DCS-gRPC](https://github.com/DCS-gRPC)). If you end up setting it up, please feel free to give me any feedback you have that I could incorporate into improving the Discord integration.
