### ISSUE TITLE
Syria missions leads to "FAILED to detect map"

### ISSUE THREAD

**Issue by Agalnov** [b1naryth1ef/sneaker#13]
Greetings again.

Really really enjoying having the Sneaker GCI available for our vSQN. Big time thanks once again and again.

This time, I write seeking help about the topic.
I see Hoggit servers running missions on Siria with Sneaker-GCI working flawlessly, but most of the missions based on Siria got stucked on "FAILED to detect map".
Eventually, some of my old missions seems to work, but for instance, latest TTI Syria-Aleppo v2.2.1a miz (as all the missions I create now) will have this problem. 
I mentioned the TTI mission, because it is easy for you to test out, I guess.

I would like to think that the isue may be related to the update that Syria map had recently... maybe..maybe not... but it is curious how some old Syria missions works while all my newest ones don´t.

Hope you are still supporting this wonderful tool, and hope for a fix, or hint to solve it. Still, we will keep enjoying it in any other map!!

As a side request... I´ve seen on some free servers with web-map support (similiar in some ways to Sneaker), that they also retreive and show information about spotted units (with time, so to know if the info is fresh or old), and also the users map-notes.
My request is mainly for the F-10 map notes, as some tools/scripts could automatically create map-notes on the F-10 map, when the AI or Client spott a unit, aslo with the time-stamp... so if SNEAKER GCI could retrieve and display these notes, we could get something similar. 

Thanks a lot, and keep it up!!!

**Comment by b1naryth1ef** [comment]
If you check the web console there should be two numbers printed (a latitude/longitude coordinate). Could you screenshot or copy those here? This is a failure in the automatic [map detection code](https://github.com/b1naryth1ef/sneaker/blob/master/src/App.tsx#L127-L143) which just compares a rough bounding box for each map, so should be an easy fix once I can see where its going wrong.

F-10 notes are not available via Tacview unfortunately. There has been talk in the past of supporting or moving entirely to using [DCS-gRPC](https://github.com/dcs-gRPC) which would allow for this kind of feature to be built-in, but thats not something I currently have the time for.

**Comment by Agalnov** [comment]
Cristal clear with the Map-notes. Do not worry, and sorry for raising up a request already discussed.

Regarding the Failed to detect map:
This are snapshots from 2 missions in Syria (I can provide Mix if required)
![TTI Syria -Aleppo v2 2 1a](https://user-images.githubusercontent.com/97795671/166718643-0a16e2c9-7219-448b-81d5-b192d76c77da.png)
![Syria_Pendulum_Supercarrier_v1 1 5](https://user-images.githubusercontent.com/97795671/166718660-ed0e93eb-01ec-42c4-bdbc-e1c548f3e226.png)
And this one is from Persian Gulf (yep, I found one that failed!)
![Persian Gulf](https://user-images.githubusercontent.com/97795671/166718738-07ec3338-07c5-4dd8-b648-b18e6d635404.png)

Hope this snapshots are what you requested (I´m unsure... never used web console before)

Big time thanks for the support and keep it up!

**Comment by F1R4T** [comment]
hi, 

We also have this problem. Old mission files are opening. we get this error in new mission files.

![image](https://user-images.githubusercontent.com/23726522/166835675-7c51731c-d8b6-4061-a4f3-fce583f8d711.png)
![image](https://user-images.githubusercontent.com/23726522/166835772-acef9291-c156-484e-9f0c-71be3e108d62.png)

**Comment by b1naryth1ef** [comment]
Thanks, thats exactly what I needed. I've pushed a [fix](https://github.com/b1naryth1ef/sneaker/commit/6932022a79276e88d6ce08ed3afc8fa0fa89688d) to the master branch which _should_ hopefully resolve the issue. I've also generated some alpha test builds so ya'll can confirm before I cut a new release:

[sneaker-windows-amd64-0.0.7-alpha-test.zip](https://github.com/b1naryth1ef/sneaker/files/8638288/sneaker-windows-amd64-0.0.7-alpha-test.zip)
[sneaker-linux-amd64-0.0.7-alpha-test.zip](https://github.com/b1naryth1ef/sneaker/files/8638291/sneaker-linux-amd64-0.0.7-alpha-test.zip)

**Comment by Agalnov** [comment]
Interesting results in several test:
F16 - Caucasus "Free Flight"  Instant action:  (37, 39)
F16 - Caucasus "Overwhelmig force" Mission: (38, 39)
F16 - Nevada "Home on the Range" Mission: (32, -120)

I´ve tested here and there... looking randomly for old created missions (on instant action or Missions from vanilla DCS), and all the failing ones so far belongs to the F-16... although I´m sure the issue has nothing to do with the Airframe you fly...

Not wanting to test without a full method/purpose, I´ve posted those 3 examples, but I´ve tested a loooot more, and 99% of the missions (including the failing ones I reported the other day) work flawlessly!!

If you have any suggestion on what to test/seek for, I´ll be glad to help you out hunting down those pair of numbers from failing missions.

All in all, test version looks great!

Thanks a lot for the great support!

**Comment by F1R4T** [comment]
> Thanks, thats exactly what I needed. I've pushed a [fix](https://github.com/b1naryth1ef/sneaker/commit/6932022a79276e88d6ce08ed3afc8fa0fa89688d) to the master branch which _should_ hopefully resolve the issue. I've also generated some alpha test builds so ya'll can confirm before I cut a new release:
> 
> [sneaker-windows-amd64-0.0.7-alpha-test.zip](https://github.com/b1naryth1ef/sneaker/files/8638288/sneaker-windows-amd64-0.0.7-alpha-test.zip) [sneaker-linux-amd64-0.0.7-alpha-test.zip](https://github.com/b1naryth1ef/sneaker/files/8638291/sneaker-linux-amd64-0.0.7-alpha-test.zip)

Hi,

Tested and working as fine on Syria new missions.
Thanks for help!

**Comment by b1naryth1ef** [comment]
I released v0.0.7 which should also include a fix for the above Caucasus problems you saw. Nevada is not currently supported, I'll open a separate issue later to add that later on. Thanks for the report and help tracking this down!

**Comment by kestrels-seeker** [comment]
@b1naryth1ef 
Hey hello. Started getting and Error. Syria map (with the new miz file, old one is working correctrly)
![image](https://user-images.githubusercontent.com/36270674/190889417-937f9fba-2a42-4acd-b425-2c4aa0c0974f.png)
![image](https://user-images.githubusercontent.com/36270674/190889426-d6501c72-1e8d-4ba4-8180-b2c30e1de737.png)

Hm.. Looks like when there are carriers (any) on the map -> sneaker fails to show the map. The same miz but without carriers -> everything is fine

some more tests. It seems that west and south from this carrier position is unknown area for sneaker
![image](https://user-images.githubusercontent.com/36270674/190894715-126f3662-2d1d-4a1b-b812-59a679dde580.png)
