### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by Heater711** [b1naryth1ef/sneaker#3]
Hello, How can I install this on my DCS server ?

**Comment by b1naryth1ef** [comment]
Install process is as follows:

**Prequisites**
- TacView installed on the server & Real-time telemetry enabled (https://www.tacview.net/documentation/realtime/en/). For now sneaker does not support utilizing a password for this, but will in the future.

**Configuration**

You will need to create a configuration file that contains a list of servers and their corresponding hostnames (for non-standard TacView configuration you'd need to include a port as well, e.g. `localhost:1234`).

```json
{
  "servers": [
    {
      "name": "myserver",
      "hostname": "localhost",
      "enable_friendly_ground_units": true,
      "enable_enemy_ground_units": false
    }
  ]
}
```

1. Download the latest release for your OS from [here](https://github.com/b1naryth1ef/sneaker/releases/) (I probably need to push a new build, I'll see about doing that soon).
2. Start the server: `sneaker --bind 0.0.0.0:7788 --config config.json` would then result in the sneaker interface being available via port 7788.

I have not tested extensively on windows so there may be some stuff thats just broken, but I'd be curious to hear.

**Comment by Heater711** [comment]
Hello,
thanks for your reply ;)

I've created a file named config.json inside the root of sneaker folder.

How can I start the server ? via command pront inside the root ? Like this

![sneaker](https://user-images.githubusercontent.com/72864507/134920488-2e33e37d-0029-4848-9c29-c4b9580da71e.png)
![sneaker2](https://user-images.githubusercontent.com/72864507/134920490-d9a86cb2-a47b-4754-9493-2e53d842dcca.png)

**Comment by Heater711** [comment]
Maybe is running. I will let you know

**Comment by MartinMac1982** [comment]
Sorry for bumping this , but where do I specify the URL that I want this to use or is this a preset URL and if so what is it thanks, determined to get this to work.

**Comment by b1naryth1ef** [comment]
You can configure how the server binds locally (e.g. the interface/port) via the `--bind 0.0.0.0:7788` CLI flag.

**Comment by MartinMac1982** [comment]
Thanks for the reply , I have it set up this way and the ports are open and communicating , the issue I am having is determining how to link it to a certain website/url. I have a free domain I can use but that's the part that's confusing me. Thanks again.
