### ISSUE TITLE
Tablet/Phone interface

### ISSUE THREAD

**Issue by Floydii** [b1naryth1ef/sneaker#7]
Currently there does not appear to be a way to _reliably_ zoom, place a cursor for bullseye or draw lines when viewing the page on a tablet or phone.

Being able to pinch zoom, tap a point to see the bulls and press/drag for lines would be excellent. I'm currently trying to use a 10 inch tablet as a bootleg SA page for the F15 so displaying on a monitor isn't an option.

**Comment by b1naryth1ef** [comment]
Fixed in [d36949](https://github.com/b1naryth1ef/sneaker/commit/d36949b14a93de19c595d0bc274b55a8d0c9b89b)
